name: haskell-opengl
version: 0.1.0.0
github: "2bd4-pbp-01/pbp_12_experiment"
license: MIT
author: "Muhammad Fajri"
maintainer: "example@example.com"
copyright: "2024 Kelompok 1 PBP-TE"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-opengl#readme>

dependencies:
  - base >= 4.7 && < 5
  - OpenGL
  - GLUT
  - GLFW-b
  - bytestring

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-opengl-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-opengl

tests:
  haskell-opengl-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-opengl
